version: '3'

networks:
  proxy:
    external: true

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $DOCKERDIR/data/conf:/etc/traefik
      - $DOCKERDIR/data/certs:/etc/traefik/certs
      - $DOCKERDIR/data/logs:/var/log/traefik:rw
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.traefik-secure.entrypoints=websecure"
      - "traefik.http.routers.traefik-secure.middlewares=default-chain@file,traefik-auth@file,rate-limit@file"
      - "traefik.http.routers.traefik-secure.rule=Host(`$HOSTNAME0.$DOMAINNAME`)"
      - "traefik.http.routers.traefik-secure.service=api@internal"
      #- "traefik.http.routers.traefik-secure.tls.certresolver=produktion"        # Certificates via letsencrypt
      - "traefik.http.routers.traefik-secure.tls.options=modern@file"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.services.traefik.loadbalancer.sticky.cookie.httpOnly=true"
      - " traefik.http.services.traefik.loadbalancer.sticky.cookie.secure=true"

      #- "traefik.http.services.traefik.loadbalancer.server.port=8080"
      #- "traefik.http.routers.traefik-secure.middlewares=rate-limit@file,secHeaders@file,authelia@docker"
